barebox: fix USB
USB is not working due to missing OTG and USB NOP support
in barebox, leading to that message at boot:
ERROR: dwc2 20980000.usb@7e980000.of: probe failed: Function not implemented

From barebox 'USB_NOP_XCEIV' configuration help:
  This driver is to be used by all the usb transceiver which are either
  built-in with usb ip or which are autonomous and doesn't require any
  phy programming such as ISP1x04 etc.

'USB_DWC2_GADGET' configuration allows to use USB OTG and not only host
mode.

Signed-off-by: Gilles DOFFE <g.doffe@gmail.com>